<?php

namespace poprigun\chat\models\forms;
use poprigun\chat\models\PoprigunChatDialog;
use poprigun\chat\models\PoprigunChatMessage;
use yii\base\Model;

/**
 * User: poprigun
 */
class MessageForm extends Model{

    public $dialog_id;
    public $receiver_id;
    public $sender_id;
    public $message;
    public $title;
    public $scenario;
    public $message_type;

    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $this->setScenario(!empty($this->scenario) ? $this->scenario : 'to_user');
    }


    public function rules() {

        return [
            [['message',  'receiver_id', 'sender_id'], 'required', 'on' => ['to_user','to_dialog']],
            ['dialog_id', 'required', 'on' => 'to_dialog'],

            [['message','title'], 'filter', 'filter' => 'trim', 'on' => ['to_user','to_dialog']],
            ['message', 'string', 'max' => 2000 , 'on' => ['to_user','to_dialog']],
            ['title', 'string', 'max' => 128 , 'on' => ['to_user','to_dialog']],

            [['dialog_id', 'sender_id', 'message_type'], 'integer' , 'on' => ['to_user','to_dialog']],
        ];
    }

    /**
     * Save message
     *
     * @return bool|Message
     */
    public function saveMessage(){

        $receivers = explode(',',$this->receiver_id);

        if($this->scenario == 'to_user'){
            $dialog = PoprigunChatDialog::isUserDialogExist($this->sender_id, $receivers, $this->message_type);
        }else{
            $dialog = PoprigunChatDialog::getDialog($this->sender_id, $this->dialog_id);
        }

        if(!$dialog){
            $dialog = PoprigunChatDialog::createDialog($this->sender_id, $receivers, $this->title, $this->message_type);
        }

        return $dialog->sendMessage($this->sender_id,$this->message,$receivers);
    }
}
