<?php

namespace poprigun\chat\models;


use poprigun\chat\Chat;

class ActiveRecord extends \yii\db\ActiveRecord
{
    const DATE_FORMAT = "Y-m-d H:i:s";

    protected $pchatSettings;

    public function init(){

        $this->pchatSettings = \Yii::$app->controllerMap['pchat-settings'];
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert){

        $date =  new \DateTime('now', new \DateTimeZone('UTC'));

        if($this->isNewRecord)
            $this->created_at = $date->format(self::DATE_FORMAT);
        else
            $this->updated_at = $date->format(self::DATE_FORMAT);

        return parent::beforeSave($insert);
    }
}
